version: '{build}'

platform: Any CPU

clone_folder: c:\go\src\github.com\0xAwn\dissident

environment:
  GOPATH: c:\go

install:
- set PATH=%GOPATH%\bin;c:\go\bin;%PATH%
- go version

build_script:
- go build -race -v .

test_script:
    - go test -race -v ./coffer/...
    - go test -race -v ./crypto/...
    - go test -race -v ./data/...
    - go test -race -v ./stdin/...
    - go test -race -v ./

notifications:
- provider: Slack
  incoming_webhook:
    secure: ug7DnsdAJi4lzD/jgdD50X9iX8j9CO9DwoEAIA90WM01ppBJIQovhz0ndmmBXHZRI36pnojw8Qn+jD0PqWfLAO9Mmtj/aPgIGqnj//uzXVvWL0a5ps8s4C0iOoMxqVrlsGZN1E2hJSsesgKpuFzEhw==
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true
